name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build and Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Change if your site files are in a different directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
